[package]
name = "okc-agents"
version = "0.1.1"
authors = ["DDoSolitary <DDoSolitary@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
ctrlc = "3.1.7"
futures-util = "0.3.8"
lazy_static = "1.4.0"
slog = "2.5.2"
slog-async = "2.5.0"
slog-envlogger = "2.2.0"
slog-term = "2.6.0"
tokio = { version = "0.2.23", features = ["fs", "io-std", "io-util", "macros", "stream", "tcp", "time", "uds"] }

[profile.release]
lto = true
