[package]
name = "okc-agents"
version = "0.1.2"
authors = ["DDoSolitary <DDoSolitary@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.13.0"
clap = "2.33.3"
futures-util = "0.3.8"
lazy_static = "1.4.0"
libc = "0.2.80"
slog = "2.5.2"
slog-async = "2.5.0"
slog-envlogger = "2.2.0"
slog-term = "2.6.0"
tokio = { version = "0.2.24", features = ["fs", "io-std", "io-util", "macros", "process", "signal", "stream", "tcp", "time", "uds"] }

[profile.release]
lto = true
