[package]
name = "okc-agents"
version = "0.1.0"
authors = ["DDoSolitary <DDoSolitary@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["fs", "io-std", "io-util", "macros", "stream", "tcp", "time", "uds"] }
futures-util = "0.3.5"
base64 = "0.12.3"
ctrlc = "3.1.5"
