[package]
name = "okc-agents"
version = "0.1.0"
authors = ["DDoSolitary <DDoSolitary@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.12.3"
ctrlc = "3.1.5"
futures-util = "0.3.5"
lazy_static = "1.4.0"
slog = "2.5.2"
slog-async = "2.5.0"
slog-envlogger = "2.2.0"
slog-term = "2.6.0"
tokio = { version = "0.2.22", features = ["fs", "io-std", "io-util", "macros", "stream", "tcp", "time", "uds"] }
