on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - env:
          CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang
          RUSTFLAGS: -C link-arg=-Wl,-rpath=/data/data/com.termux/files/usr/lib -C link-arg=-Wl,--enable-new-dtags
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add aarch64-linux-android
          cargo build --release --target=aarch64-linux-android
