on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add aarch64-linux-android
          ./build-termux.sh
      - uses: actions/upload-artifact@master
        with:
          name: Binary
          path: target/aarch64-linux-android/debug/okc-ssh-agent
